# Generated by Django 4.1.5 on 2023-01-17 11:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventprofile",
            name="profile_avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Profile avatar"
            ),
        ),
    ]
