# Generated by Django 4.1.5 on 2023-01-18 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_eventprofile_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventprofile",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        30, "Last name must be at least 3 characters long"
                    )
                ],
                verbose_name="Last Name",
            ),
        ),
    ]
