# Generated by Django 4.1.5 on 2023-01-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_eventprofile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Unpicked", "Unpicked"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                ],
                default="Unpicked",
                max_length=8,
                verbose_name="Gender",
            ),
        ),
    ]
