# Generated by Django 4.1.5 on 2023-01-17 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_eventprofile_profile_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "topic",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, message="Topic must contain at least 2 characters"
                            )
                        ],
                        verbose_name="Message topic",
                    ),
                ),
                (
                    "message_text",
                    models.TextField(
                        max_length=2500,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, message="Field must contain at least 2 characters"
                            )
                        ],
                        verbose_name="Message text",
                    ),
                ),
                ("read", models.BooleanField(default=False, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="accounts.eventprofile",
                        verbose_name="Message receiver",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.eventprofile",
                        verbose_name="Message sender",
                    ),
                ),
            ],
            options={
                "ordering": ["read", "-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "title",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Title must be at least 2 characters long"
                            )
                        ],
                        verbose_name="Interest title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2500,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Description must be at least 2 characters long"
                            )
                        ],
                        verbose_name="Interest description",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "interest_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.eventprofile",
                        verbose_name="Interest creator",
                    ),
                ),
            ],
        ),
    ]
