# Generated by Django 4.1.5 on 2023-01-13 10:08

import MyEventWorld.core.validators.file_size_validator
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "title",
                    models.CharField(
                        max_length=90,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Title must be at least 3 characters long"
                            )
                        ],
                        verbose_name="Event title",
                    ),
                ),
                (
                    "event_description",
                    models.TextField(
                        max_length=2500,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Description must be at least 3 characters long"
                            )
                        ],
                        verbose_name="Event description",
                    ),
                ),
                (
                    "event_category",
                    models.CharField(
                        choices=[
                            ("Sport", "Sport"),
                            ("Culture", "Culture"),
                            ("Entertainment", "Entertainment"),
                            ("Nature", "Nature"),
                            ("Other", "Other"),
                        ],
                        max_length=13,
                    ),
                ),
                (
                    "event_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_avatars/",
                        validators=[
                            MyEventWorld.core.validators.file_size_validator.validate_file_less_than_3mb
                        ],
                        verbose_name="Event picture",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.eventprofile",
                        verbose_name="Event creator",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-updated"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "review_title",
                    models.CharField(
                        max_length=15,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Review title",
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        max_length=2500,
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="Review text",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "review_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.eventprofile",
                        verbose_name="Review creator",
                    ),
                ),
                (
                    "review_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "unique_together": {("review_creator", "review_for")},
            },
        ),
    ]
