# Generated by Django 4.1.5 on 2023-01-18 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_event_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(
                help_text="Keep in mind this is one-time review and you wont be able to edit it!",
                max_length=2500,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="Review text",
            ),
        ),
    ]
